.uno/CodeCompletion/ux11/MainView.g.uno
.uno/CodeCompletion/ux11/TabHeader.g.uno
.uno/CodeCompletion/ux11/TabIcon.g.uno
.uno/CodeCompletion/ux11/PagePlaceholder.g.uno
.uno/CodeCompletion/ux11/ColorPalette.g.uno
.uno/CodeCompletion/ux11/CoursePage.g.uno
.uno/CodeCompletion/ux11/Course.g.uno
.uno/CodeCompletion/ux11/HidingPanel.g.uno
.uno/CodeCompletion/ux11/Student.unoproj.g.uno